[build.environment]
NODE_VERSION = "18"

[build]
publish = "dist"
command = "pnpm run build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/site.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"
